# The Docker image that will be used to build your app
image: node:18

pages:
  script:
    # You can replace this with your actual build commands if necessary
    - echo "hello"
    - mkdir public
    - cp -r Visualizer/* public/  # Copy the contents of Visualizer to the public folder
  artifacts:
    paths:
      - public  # GitLab Pages expects your static site files to be in the public/ directory
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
